### ISSUE TITLE
可以預測 BTC Market 走向的 API

### ISSUE THREAD

**Issue by wayne5540** [wayne5540/poloniex-toy#1]
btcmarkets.net 反應很慢，應該可以根據 poloniex 或是 kraken 的數據預測短時間內的 btcmarkets 價格走向，目的是

1. 逃離大災難
2. 跟上大牛市

不適用於短頻交易

### MVP 版本：

* 抓 20 分鐘內的 BTC 走向
* 比對當前的 BTC rate
* 回傳價格相差的 percentage

### API Proposal

* Request

```
GET /bmpredict
```

* Response

```js
{
  percentageChange: 0.21 // since last 20 mins
  poloniex: 3800 // AUD
  btcMarket: 4000 // AUD
  valueDiff: 0.05 // (btcMarket - poloniex) / btcMarket
}
```

### Bot

另外寫個 telegram bot 每一兩分鐘就掃一次這個 API，如果其他網路已經開始大跌大漲（absolute(percentageChange)）但 btc market  還沒反應 （absolute(valueDiff)） 就通知

判斷：

```
if absolute(percentageChange) > 0.05 && absolute(valueDiff) > 0.08
  send message with raw api response
esle
  do nothing
```

**Comment by wayne5540** [comment]
Poloniex: https://poloniex.com/support/api/ , 可以看 `returnChartData `

**Comment by davelee0504** [comment]
我可能用[crypto compare](https://www.cryptocompare.com/api/#-api-data-price-)
這個API可以一次拿到多個交易所的資料
再透過你說的fixer.io 轉換一下匯率吧

**Comment by davelee0504** [comment]
percentageChange: 0.21 // since last 20 mins
你這個數字是想以哪個交易所為主啊？

**Comment by wayne5540** [comment]
![LGTM](http://www.lgtm.in/p/OxyKioCUp)
